Repository gorgeousTeam6/taskify, pull requests merged in 2024-08, with the labels that each got.

#7 feat: dashboard 페이지 퍼블리싱
  containers/dashboard/id/DashboardId.tsx
  containers/dashboard/id/card/Card.module.scss
  containers/dashboard/id/chips/Chip.module.scss
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/index.module.scss
  containers/dashbord/id/chips/ChipProgress.tsx
  pages/dashboard/[id]/index.tsx
  styles/mixins/_common.scss
Labels: ✨ Feature, 🎨 HTML & CSS

#13 feat: 컬럼 생성, 관리 초대 모달
  components/ModalPortal/index.module.scss
  components/ModalPortal/index.tsx
  components/SmallModal/index.module.scss
  components/SmallModal/index.tsx
  constants/ModalConstant.ts
  containers/dashboard/id/modals/CreateModal.tsx
  containers/dashboard/id/modals/ManageModal.tsx
  hooks/useReactQuery.tsx
  pages/_document.tsx
  stores/modalStore.ts
  styles/_fonts.scss
  styles/_levels.scss
  styles/mixins/mixinModal.scss
  types/modal.d.ts
Labels: ✨ Feature, 🔥 매운맛, ⭐️ 칭찬해주세요

#14 feat: 초대받은 대시보드 퍼블리싱
  containers/myDashboard/InviteListItem/InviteListItem.module.scss
  containers/myDashboard/InviteListItem/InviteListItem.tsx
  containers/myDashboard/invitedDashboard/InvitedDashboard.module.scss
  containers/myDashboard/invitedDashboard/InvitedDashboard.tsx
Labels: ✨ Feature, 🎨 HTML & CSS

#17 Feat: 로그인 및 회원가입 기능 구현
  constants/index.ts
  containers/sign/PwdLabel.tsx
  containers/sign/SiginInForm.tsx
  containers/sign/SiginUpForm.tsx
  containers/sign/TextInputLabel.tsx
  containers/sign/TopLogoSection.tsx
  hooks/useFetechData.ts
  hooks/useSignIn.ts
  pages/_app.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  services/axios.ts
  services/postService.ts
  store/useUserStore.ts
  types/SignInForm.interface.ts
  types/SignUpForm.interface.ts
  types/User.interface.ts
  utils/encryption_Password.ts
Labels: ✨ Feature

#19 feat: 할 일 수정 & 할 일 생성 모달 제작
  assets/icongroup.ts
  containers/dashboard/id/DashboardId.tsx
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  containers/dashboard/id/modals/todoModal/TodoModal.module.scss
  pages/index.tsx
  styles/reset.scss
Labels: ✨ Feature, 미완성😖

#22 feat:대시보드 수정 페이지 퍼블리싱
  containers/dashboardEdit/DashboardEdit.module.scss
  containers/dashboardEdit/DashboardEdit.tsx
  containers/dashboardEdit/EditDashboardName/EditDashboardName.module.scss
  containers/dashboardEdit/EditDashboardName/EditDashboardName.tsx
  containers/dashboardEdit/EditInvitation/EditInvitation.module.scss
  containers/dashboardEdit/EditInvitation/EditInvitation.tsx
  containers/dashboardEdit/EditInvitation/InvitationListItem/InvitationListItem.module.scss
  containers/dashboardEdit/EditInvitation/InvitationListItem/InvitationListItem.tsx
  containers/dashboardEdit/EditMember/EditMember.module.scss
  containers/dashboardEdit/EditMember/EditMember.tsx
  containers/dashboardEdit/EditMember/MemberListItem/MemberListItem.module.scss
  containers/dashboardEdit/EditMember/MemberListItem/MemberListItem.tsx
  containers/myDashboard/DashboardList/DashboardList.module.scss
  containers/myDashboard/DashboardList/DashboardList.tsx
  containers/myDashboard/MyDashboard.module.scss
  containers/myDashboard/MyDashboard.tsx
  pages/dashboard/[id]/edit/index.tsx
  pages/mydashboard/index.tsx
Labels: ✨ Feature, 🎨 HTML & CSS, 미완성😖

#27 style: 메인페이지 반응형 스타일 적용
  constants/MainPageConstants.tsx
  containers/main/Footer/index.module.scss
  containers/main/SettingList/index.module.scss
  containers/main/SettingList/index.tsx
  containers/main/index.module.scss
  containers/main/index.tsx
Labels: 🎨 HTML & CSS

#29 feat: 할일 생성 모달 페이지에 연결
  containers/dashboard/id/DashboardId.tsx
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/modals/todoCreateModal/.TodoCreateModal.module.scss.swp
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  stores/modalStore.ts
Labels: ✨ Feature

#30 수정사항 반영 및 페이지네이션 버튼, 대시보드 생성 모달 퍼블리싱
  components/Button/ButtonChildren/index.tsx
  components/ButtonSet/index.module.scss
  components/ButtonSet/index.tsx
  components/ButtonSetForPagination/Button/index.module.scss
  components/ButtonSetForPagination/Button/index.tsx
  components/Header/HeaderDashboard/index.module.scss
  components/Header/HeaderDashboard/index.tsx
  components/Header/HeaderMain/index.module.scss
  components/Header/HeaderMain/index.tsx
  components/HeaderAndSideMenu/index.module.scss
  components/HeaderAndSideMenu/index.tsx
  components/SideMenu/SideMenuItem/index.module.scss
  components/SideMenu/index.module.scss
  components/UserIcon/index.module.scss
  components/UserIcon/index.tsx
  containers/myDashboard/CreateDashboardModal/index.module.scss
  containers/myDashboard/CreateDashboardModal/index.tsx
  pages/buttonPreview.tsx
  pages/headerAndSideMenuPreview.tsx
  types/button.d.ts
  types/userIcon.d.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#31 feat: 할일 모달 데이터 연결 및 상태/담당자 드롭다운 컴포넌트 구현
  containers/dashboard/id/card/Card.module.scss
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/dropdown/Dropdown.module.scss
  containers/dashboard/id/dropdown/Dropdown.tsx
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/Assignee/index.module.scss
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/Assignee/index.tsx
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.module.scss
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.tsx
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.module.scss
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.tsx
  containers/dashboard/id/dropdown/kebabDropdown/KebabDropdown.tsx
  containers/dashboard/id/modals/todoModal/Comment/index.module.scss
  containers/dashboard/id/modals/todoModal/Comment/index.tsx
  containers/dashboard/id/modals/todoModal/TodoModal.module.scss
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
  containers/dashboard/id/modals/todoModal/managerCard/ManagerCard.tsx
  hooks/useColumnList.ts
  hooks/useCommentList.ts
  hooks/useDashboardMember.ts
  hooks/useDetectClose.ts
  stores/todoModalStore.ts
  styles/_animations.scss
  styles/mixins/mixinDropdown.scss
  styles/mixins/mixinModal.scss
  types/comment.d.ts
  types/member.d.ts
  utils/getDate.ts
Labels: ✨ Feature

#32 feat: 나의 대시보드 페이지 데이터페칭 함수 추가
  containers/myDashboard/DashboardList/DashboardList.tsx
  containers/myDashboard/InviteListItem/InviteListItem.tsx
  containers/myDashboard/invitedDashboard/InvitedDashboard.tsx
  package-lock.json
  package.json
  types/dashboard.d.ts
  types/invitedDashboard.d.ts
Labels: ✨ Feature

#33 수정사항 반영 및 나의 대시보드 모달 2개 구현
  components/Button/index.module.scss
  components/Header/HeaderMain/index.module.scss
  components/Header/index.module.scss
  components/Header/index.tsx
  containers/myDashboard/CreateDashboardModal/index.tsx
  containers/myDashboard/InviteModal/index.module.scss
  containers/myDashboard/InviteModal/index.tsx
Labels: ✨ Feature

#34 feat: 할 일 모달 댓글 기능 구현
  containers/dashboard/id/modals/CreateModal.tsx
  containers/dashboard/id/modals/ManageModal.tsx
  containers/dashboard/id/modals/todoModal/Comment/index.module.scss
  containers/dashboard/id/modals/todoModal/Comment/index.tsx
  containers/dashboard/id/modals/todoModal/CommentForm/index.module.scss
  containers/dashboard/id/modals/todoModal/CommentForm/index.tsx
  containers/dashboard/id/modals/todoModal/TodoModal.module.scss
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
  containers/dashboard/id/modals/todoModal/mixinButton.scss
  hooks/useColumnList.ts
  hooks/useCommentList.ts
  stores/EditCommentStore.ts
Labels: ✨ Feature

#36 feat&fix: 수정사항 반영, 대시보드 초대 수락,거절 함수추가, 초대받은 대시보드 검색함수 추가
  containers/myDashboard/DashboardList/DashboardList.tsx
  containers/myDashboard/InviteListItem/InviteListItem.tsx
  containers/myDashboard/invitedDashboard/InvitedDashboard.tsx
  types/dashboard.d.ts
  types/invitedDashboard.d.ts
Labels: ✨ Feature

#39 페이지네이션 버튼 수정 및 이벤트 추가
  components/ButtonSetForPagination/Button/index.module.scss
  components/ButtonSetForPagination/Button/index.tsx
  types/button.d.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#40 feat: 할일 카드랑 수정하기 모달 연결
  assets/icongroup.ts
  assets/icons/ic_arrow_next.svg
  assets/icons/ic_arrow_previous.svg
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/dropdown/kebabDropdown/KebabDropdown.tsx
  containers/dashboard/id/modals/calendar/Calendar.module.scss
  containers/dashboard/id/modals/calendar/Calendar.tsx
  containers/dashboard/id/modals/todoCreateModal/.TodoCreateModal.module.scss.swp
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  containers/dashboard/id/modals/todoModal/TodoModal.module.scss
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
  stores/modalStore.ts
  stores/useCurrentCardStore.ts
  stores/useTodoEditModalStore.ts
  styles/_color.scss
Labels: ✨ Feature

#41 feat: 컬럼 비어있을때 empty 컴포넌트 추가
  assets/logos/EmptyGray.svg
  assets/logos/EmptyYellow.svg
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/column/EmptyColumn.tsx
Labels: ✨ Feature

#42 수정사항 반영, 버튼 modal-primary 타입 추가, 색상 선택 리스트 공통 컴포넌트 추가
  assets/icongroup.ts
  assets/icons/ic_checked.svg
  components/Button/index.module.scss
  components/ColorCircleList/index.module.scss
  components/ColorCircleList/index.tsx
  components/Header/HeaderDashboard/index.module.scss
  components/Header/HeaderMain/index.module.scss
  components/SideMenu/index.module.scss
  containers/myDashboard/CreateDashboardModal/index.tsx
  containers/myDashboard/InviteModal/index.tsx
  styles/_levels.scss
  types/button.d.ts
  types/colorCircleList.d.ts
Labels: ✨ Feature, 🎨 HTML & CSS

#43 FIX: 수정사항 적용
  assets/icongroup.ts
  components/Input/ImageInput.module.scss
  containers/mypage/EditProfileForm.module.scss
  containers/mypage/EditProfileForm.tsx
  containers/mypage/PwdChangeForm.module.scss
  containers/mypage/PwdChangeForm.tsx
  containers/sign/PwdLabel.module.scss
  containers/sign/SiginInForm.tsx
  containers/sign/SiginUpForm.tsx
  containers/sign/TopLogoSection.module.scss
  containers/sign/TopLogoSection.tsx
  pages/mypage/index.module.scss
  pages/mypage/index.tsx
  pages/signin/index.module.scss
  styles/_color.scss
Labels: 🐛 BugFix

#44 feat: 모달창 데이터 연동
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.tsx
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  stores/useCurrentCardStore.ts
  styles/mixins/mixinDropdown.scss
Labels: ✨ Feature

#46 feat: 대시보드 레이아웃 구현
  containers/dashboardLayout.module.scss
  containers/dashboardLayout.tsx
Labels: ✨ Feature, 🎨 HTML & CSS

#47 feat: 대시보드 추가 모달 추가
  containers/myDashboard/CreateDashboardModal/index.module.scss
  containers/myDashboard/CreateDashboardModal/index.tsx
  containers/myDashboard/DashboardList/DashboardList.tsx
  containers/myDashboard/invitedDashboard/InvitedDashboard.tsx
Labels: ✨ Feature

#48 feat: 드래그앤드롭 기능 구현
  containers/dashboard/id/DashboardId.tsx
  containers/dashboard/id/card/Card.module.scss
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/column/Column.tsx
  hooks/useCardList.ts
  package-lock.json
  package.json
  services/cardService.ts
  services/dragService.ts
Labels: ✨ Feature

#49 feat: 삭제 경고 모달 구현
  containers/dashboard/id/modals/deleteAlertModal/index.module.scss
  containers/dashboard/id/modals/deleteAlertModal/index.tsx
  services/columnService.ts
Labels: ✨ Feature

#50 feat: dashboard 페이지 로그인 상태에 따른 리다이렉트 구현
  pages/dashboard/[id]/index.tsx
Labels: ✨ Feature

#51 fix: 메인 페이지 배열 렌더링 컴포넌트에 key prop 추가
  containers/main/index.tsx
Labels: 🐛 BugFix

#53 feat: 모달 데이터 연동
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.module.scss
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.tsx
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.module.scss
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.tsx
  styles/mixins/mixinDropdown.scss
Labels: ✨ Feature, 미완성😖

#54 fix: 현재 시간으로 나오던 에러 수정
  utils/getDate.ts
Labels: 🐛 BugFix

#55 FIX: /mypage, /sign 페이지 수정사항 적용(코드 리뷰 피드백 적용 및 멘토링 수정)
  components/Input/ImageInput.module.scss
  components/Input/ImageInput.tsx
  components/Input/PwdInput.module.scss
  components/Input/PwdInput.tsx
  containers/mypage/EditProfileForm.module.scss
  containers/mypage/EditProfileForm.tsx
  containers/mypage/PwdChangeForm.module.scss
  containers/mypage/PwdChangeForm.tsx
  containers/mypage/index.module.scss
  containers/mypage/index.tsx
  containers/sign/PwdLabel.module.scss
  containers/sign/PwdLabel.tsx
  containers/sign/SiginInForm.tsx
  containers/sign/SiginUpForm.tsx
  containers/sign/SignForm.module.scss
  containers/sign/TextInputLabel.tsx
  containers/sign/TopLogoSection.module.scss
  containers/sign/TopLogoSection.tsx
  containers/sign/signin/index.module.scss
  containers/sign/signin/index.tsx
  containers/sign/signup/index.tsx
  hooks/useUpdateProfile.ts
  pages/mypage/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  services/putService.ts
Labels: 🐛 BugFix

#56 feat: 토스트 컴포넌트 구현
  assets/icons/ic_close.svg
  components/Toast/ToastItem.tsx
  components/Toast/ToastList.tsx
  components/Toast/index.module.scss
  hooks/useToast.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  stores/toastStore.ts
  styles/_animations.scss
  styles/_color.scss
  styles/_levels.scss
  types/toast.d.ts
Labels: ✨ Feature

#57 헤더 수정사항 반영
  components/Header/HeaderDashboard/index.module.scss
  components/Header/HeaderMain/index.module.scss
Labels: 🐛 BugFix, 🎨 HTML & CSS

#58 feat: 무한스크롤 기능 구현
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/column/Column.tsx
  hooks/useInfiniteScroll.ts
  package-lock.json
  package.json
  pages/_app.tsx
  styles/reset.scss
  types/parameter.ts
Labels: ✨ Feature

#60 style: add chip 컴포넌트 색상 변경
  assets/icons/ic_add_chip.svg
  containers/dashboard/id/chips/Chip.module.scss
  containers/dashboard/id/chips/ChipAdd.tsx
  styles/_color.scss
Labels: 🎨 HTML & CSS

#61 style: profile 컴포넌트 수정
  components/ProfileIcon/ProfileIcon.module.scss
  components/ProfileIcon/ProfileIcon.tsx
  utils/getBackgroundColor.ts
Labels: 🎨 HTML & CSS

#62 FEET: 로그인, 회원가입, 비번 변경 Toast 생성 및 동의 모달 추가
  components/Input/PwdInput.module.scss
  containers/mypage/EditProfileForm.module.scss
  containers/mypage/EditProfileForm.tsx
  containers/mypage/PwdChangeForm.tsx
  containers/sign/AgreeModal.module.scss
  containers/sign/AgreeModal.tsx
  containers/sign/PwdLabel.module.scss
  containers/sign/SiginInForm.tsx
  containers/sign/SiginUpForm.tsx
  containers/sign/TopLogoSection.module.scss
  containers/sign/signin/index.module.scss
  hooks/SignInError.ts
  hooks/useSignIn.ts
Labels: 🐛 BugFix, ✨ Feature

#66 feat: 미들웨어를 이용한 리다이렉트 구현
  hooks/useSignIn.ts
  middleware.ts
Labels: ✨ Feature

#67 fix: 할일 생성 모달 기능 수정
  containers/dashboard/id/DashboardId.tsx
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  stores/TodoCreateModalStore.ts
  stores/modalStore.ts
  types/formValue.d.ts
Labels: 🐛 BugFix

#68 fix: 할일 수정 모달 파일 post 추가 및 수정
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  stores/ImageInputStore.ts
Labels: 🐛 BugFix

#69 style: fixedmenu로 레이아웃 수정
  containers/dashboard/id/DashboardId.tsx
  containers/dashboardLayout.module.scss
  containers/dashboardLayout.tsx
Labels: 🎨 HTML & CSS

#70 refactor: 댓글 작성자 구분 및 레이아웃 변경
  components/ProfileIcon/ProfileIcon.tsx
  containers/dashboard/id/modals/todoModal/Comment/index.module.scss
  containers/dashboard/id/modals/todoModal/Comment/index.tsx
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.tsx
  containers/dashboard/id/modals/todoModal/mixinButton.scss
  styles/_color.scss
Labels: 🎨 HTML & CSS, ♻ Refactor

#71 style: 태그 랜덤색상 추가
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/chips/Chip.module.scss
  styles/_variable.scss
  utils/getRandomTagColor.ts
Labels: ♻ Refactor

#72 feat: 삭제 경고 알림 모달 구현
  components/SmallModal/index.module.scss
  components/SmallModal/index.tsx
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/column/Column.tsx
  containers/dashboard/id/modals/CreateModal.tsx
  containers/dashboard/id/modals/ManageModal.tsx
  containers/dashboard/id/modals/deleteAlertModal/index.tsx
  services/columnService.ts
  stores/useDeleteAlertModalStore.ts
  utils/getRandomTagColor.ts
Labels: ✨ Feature

#75 refactor: create modal 에러메시지 토스트로 띄우기
  containers/dashboard/id/modals/CreateModal.tsx
Labels: ♻ Refactor

#76 fix: 담당자 없을때 렌더링 조건 추가
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.tsx
Labels: 🐛 BugFix

#78 style: 카드 레이아웃 수정
  containers/dashboard/id/card/Card.tsx
Labels: 🎨 HTML & CSS

#77 fix: 댓글 공백 들어가지 않도록 수정
  containers/dashboard/id/modals/todoModal/CommentForm/index.tsx
Labels: 🐛 BugFix

#79 feat&fix: 대시보드 수정페이지 스타일링추가,무한스크롤 함수 추가, 초대하기 함수 수정, 페이지네이션 컴포넌트 추가
  assets/icongroup.ts
  assets/icons/ic_add_box_white.svg
  components/Pagination/index.module.scss
  components/Pagination/index.tsx
  containers/dashboardEdit/DashboardEdit.module.scss
  containers/dashboardEdit/DashboardEdit.tsx
  containers/dashboardEdit/EditDashboardName/EditDashboardName.module.scss
  containers/dashboardEdit/EditDashboardName/EditDashboardName.tsx
  containers/dashboardEdit/EditInvitation/EditInvitation.module.scss
  containers/dashboardEdit/EditInvitation/EditInvitation.tsx
  containers/dashboardEdit/EditMember/EditMember.module.scss
  containers/dashboardEdit/EditMember/EditMember.tsx
  containers/dashboardEdit/EditMember/MemberListItem/MemberListItem.tsx
  containers/myDashboard/CreateDashboardModal/index.tsx
  containers/myDashboard/DashboardList/DashboardList.module.scss
  containers/myDashboard/DashboardList/DashboardList.tsx
  containers/myDashboard/InviteModal/index.tsx
  containers/myDashboard/MyDashboard.module.scss
  containers/myDashboard/MyDashboard.tsx
  containers/myDashboard/invitedDashboard/InvitedDashboard.module.scss
  containers/myDashboard/invitedDashboard/InvitedDashboard.tsx
  hooks/usePagination.ts
Labels: 🐛 BugFix, ✨ Feature, 🎨 HTML & CSS, ♻ Refactor

#80 fix: dnd 콘솔 에러 수정
  containers/dashboard/id/DashboardId.tsx
  containers/dashboard/id/card/Card.module.scss
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/column/Column.tsx
  next.config.mjs
  package-lock.json
  package.json
  services/dragService.ts
Labels: 🐛 BugFix

#82 fix: 모달 내 드롭 다운 z-index 수정
  containers/dashboard/id/dropdown/Dropdown.module.scss
Labels: 🐛 BugFix

#84 feat: 할일 모달에 카드 삭제 기능 추가
  containers/dashboard/id/dropdown/kebabDropdown/KebabDropdown.tsx
  containers/dashboard/id/dropdown/kebabDropdown/kebabDropdown.module.scss
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
  services/cardService.ts
Labels: ✨ Feature

#86 feat: 헤더 프로필 드롭다운 구현
  components/profileDropdown/index.module.scss
  components/profileDropdown/index.tsx
Labels: ✨ Feature

#87 fix: 할일 수정 모달 담당자 없을 시 이미지 업로드 문제 해결
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  types/modalPost.d.ts
Labels: 🐛 BugFix, ✨ Feature

#90 FIX: /mypage, Toast, Modal 오류 수정
  components/Input/PwdInput.module.scss
  containers/mypage/EditProfileForm.module.scss
  containers/mypage/EditProfileForm.tsx
  containers/mypage/PwdChangeForm.module.scss
  containers/mypage/PwdChangeForm.tsx
  containers/mypage/index.module.scss
  containers/mypage/index.tsx
  containers/sign/AgreeModal.module.scss
  containers/sign/AgreeModal.tsx
  containers/sign/SiginInForm.tsx
  containers/sign/SiginUpForm.tsx
  package-lock.json
  package.json
  stores/modalStore.ts
Labels: 🐛 BugFix

#93 feat: 해시태그 입력 기능 구현
  containers/dashboard/id/modals/components/ hastagsInput/HashtagsInput.module.scss
  containers/dashboard/id/modals/components/ hastagsInput/HashtagsInput.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
Labels: 🐛 BugFix, ✨ Feature

#94 fix: 프로필 아이콘 크기 수정
  components/ProfileIcon/ProfileIcon.module.scss
  components/ProfileIcon/ProfileIcon.tsx
  components/profileDropdown/index.module.scss
Labels: 🐛 BugFix

#95 feat: 폼 유효성 검사
  containers/dashboard/id/modals/components/ hastagsInput/HashtagsInput.module.scss
  containers/dashboard/id/modals/components/ hastagsInput/HashtagsInput.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
Labels: ✨ Feature

#97 feat: 컬럼 스타일 수정
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/column/Column.tsx
Labels: 🎨 HTML & CSS

#103 feat: 404 페이지 구현
  assets/images/404.png
  containers/404/404.module.scss
  containers/404/index.tsx
  pages/404.tsx
  public/404.png
  public/404gray.png
  public/404white.png
Labels: ✨ Feature, 🎨 HTML & CSS

#102 feat: 카드 삭제 토스트 추가
  containers/dashboard/id/dropdown/kebabDropdown/KebabDropdown.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
Labels: ✨ Feature

#98 style: 할일 모달 태그 컬러 변경
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
Labels: 🎨 HTML & CSS

#99 style: 톱니바퀴 hover 애니메이션 추가
  containers/dashboard/id/column/Column.module.scss
  styles/_animations.scss
Labels: 🎨 HTML & CSS

#108 fix: 에러 해결
  containers/dashboard/id/modals/components/hastagsInput/HashtagsInput.module.scss
  containers/dashboard/id/modals/components/hastagsInput/HashtagsInput.tsx
  middleware.ts
Labels: 🐛 BugFix

#105 style: 메인 페이지 버튼 스타일 수정
  containers/main/LoginButton/index.module.scss
Labels: 🎨 HTML & CSS

#107 Chore: 수정사항 적용 및 로그아웃 기능 구현
  components/Input/ImageInput.module.scss
  components/Input/ImageInput.tsx
  components/Input/PwdInput.module.scss
  components/profileDropdown/index.tsx
  containers/mypage/EditProfileForm.module.scss
  containers/mypage/EditProfileForm.tsx
  containers/mypage/PwdChangeForm.module.scss
  containers/mypage/index.module.scss
  package-lock.json
  package.json
Labels: 🐛 BugFix, ✨ Feature

#110 fix: 에러 해결
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
Labels: 🐛 BugFix

#113 Fix: 수정사항 적용 중(현재 진행형)
  components/Input/ImageInput.module.scss
Labels: 🐛 BugFix

#116 style: 대시보드 페이지 다크모드 적용
  assets/icons/ic_kebab.svg
  components/ProfileIcon/ProfileIcon.module.scss
  components/SmallModal/index.module.scss
  components/SmallModal/index.tsx
  components/profileDropdown/index.module.scss
  components/profileDropdown/index.tsx
  containers/404/404.module.scss
  containers/404/index.tsx
  containers/dashboard/id/card/Card.module.scss
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/chips/Chip.module.scss
  containers/dashboard/id/chips/ChipNum.tsx
  containers/dashboard/id/column/Column.module.scss
  containers/dashboard/id/dropdown/Dropdown.module.scss
  containers/dashboard/id/dropdown/Dropdown.tsx
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/Assignee/index.module.scss
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/Assignee/index.tsx
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.module.scss
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.tsx
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.module.scss
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.tsx
  containers/dashboard/id/dropdown/kebabDropdown/KebabDropdown.module.scss
  containers/dashboard/id/dropdown/kebabDropdown/KebabDropdown.tsx
  containers/dashboard/id/modals/deleteAlertModal/index.module.scss
  containers/dashboard/id/modals/deleteAlertModal/index.tsx
  containers/dashboard/id/modals/todoModal/Comment/index.module.scss
  containers/dashboard/id/modals/todoModal/Comment/index.tsx
  containers/dashboard/id/modals/todoModal/CommentForm/index.module.scss
  containers/dashboard/id/modals/todoModal/CommentForm/index.tsx
  containers/dashboard/id/modals/todoModal/TodoModal.module.scss
  containers/dashboard/id/modals/todoModal/TodoModal.tsx
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.module.scss
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.tsx
  public/404gray.png
  public/card-404.png
  styles/_color.scss
  styles/mixins/mixinModal.scss
Labels: 🎨 HTML & CSS

#117 style : 할일 생성 / 수정모달 다크모드 적용
  containers/dashboard/id/modals/components/hastagsInput/HashtagsInput.module.scss
  containers/dashboard/id/modals/components/hastagsInput/HashtagsInput.tsx
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.tsx
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
Labels: 🎨 HTML & CSS

#130 Fix: Toast, Imageinput 수정
  containers/mypage/EditProfileForm.module.scss
  containers/mypage/EditProfileForm.tsx
  containers/sign/SiginInForm.tsx
  hooks/SignInError.ts
  hooks/useSignIn.ts
Labels: 🐛 BugFix

#137 Fix: 다크모드 로고 수정 및 미리보기 이미지 닉네임 설정
  components/DropdownProfile/index.tsx
  components/Header/HeaderDashboard/MemberList/index.tsx
  components/Input/ImageInput.tsx
  components/ProfileIcon/ProfileIcon.tsx
  containers/mypage/EditProfileForm.tsx
  containers/sign/TopLogoSection.module.scss
  containers/sign/TopLogoSection.tsx
  containers/sign/signin/index.module.scss
Labels: 🐛 BugFix, 🎨 HTML & CSS

#141 style: 모달들 input 스타일 수정
  components/Input/ImageInput.module.scss
  components/Input/ImageInput.tsx
  components/SmallModal/index.module.scss
  containers/dashboard/id/dropdown/SelectAssigneeDropdown/index.module.scss
  containers/dashboard/id/dropdown/SelectProgressDropdown/index.module.scss
  containers/dashboard/id/modals/components/hastagsInput/HashtagsInput.module.scss
  containers/dashboard/id/modals/todoCreateModal/TodoCreateModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.module.scss
  containers/dashboard/id/modals/todoEditModal/TodoEditModal.tsx
  containers/dashboard/id/modals/todoModal/CommentForm/index.module.scss
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.module.scss
Labels: 🎨 HTML & CSS

#143 feat: 로딩처리 추가
  containers/dashboardEdit/EditDashboardName/EditDashboardName.tsx
  containers/dashboardEdit/EditInvitation/EditInvitation.tsx
  containers/dashboardEdit/EditMember/EditMember.tsx
  containers/myDashboard/DashboardList/DashboardList.tsx
  containers/myDashboard/invitedDashboard/InvitedDashboard.module.scss
  containers/myDashboard/invitedDashboard/InvitedDashboard.tsx
Labels: ✨ Feature

#144 style: 대시보드 페이지에서 프로필 아이콘 사이즈 수정
  components/ProfileIcon/ProfileIcon.module.scss
  components/ProfileIcon/ProfileIcon.tsx
  containers/dashboard/id/card/Card.tsx
  containers/dashboard/id/modals/todoModal/Comment/index.tsx
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.module.scss
  containers/dashboard/id/modals/todoModal/assigneeCard/AssigneeCard.tsx
Labels: 🎨 HTML & CSS

#146 feat: OG태그 추가
  pages/_document.tsx
  public/og_image.png
Labels: ✨ Feature

#147 fix: 대시보드페이지, 대시보드 수정페이지 패딩 수정
  containers/dashboardEdit/DashboardEdit.module.scss
  containers/myDashboard/MyDashboard.module.scss
Labels: 🎨 HTML & CSS

#142 docs: README.md 틀 작성
  README.md
Labels: 📝 Docs

#148 docs: README.md 수정
  README.md
Labels: 📝 Docs

#150 Fix: 이미지 수정
  containers/dashboardEdit/EditMember/MemberListItem/MemberListItem.tsx
Labels: 🐛 BugFix

#151 docs: README.md 수정
  README.md
Labels: 📝 Docs

#152 docs: README.md 수정
  README.md
Labels: 📝 Docs

#153 docs: README.md 수정
  README.md
Labels: 📝 Docs
